Fix wxPython 4 compatibility issues
Removed deprecated wxPython 3 methods that are not available in wxPython 4:
- Removed SetSashSize() call (sash size is now calculated automatically)
- Removed wx.NullBitmap parameter from AddTool() (bmpDisabled param removed in wx4)
- Changed SetToolTipString() to SetToolTip() (old method removed in wx4)

This fixes the AttributeError: 'SplitterWindow' object has no attribute 'SetSashSize'
and other compatibility issues when running with wxPython 4.